platform :ios, '8.0'

target 'LottieDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for LottieDemo
  pod 'lottie-ios'
end

